project:
  type: website

website:
  title: "Data in Public Health"
  description: "Accessible, actionable data science to achieve health equity"
  navbar:
    title: false
    background: primary
    search: true
    right:
      - icon: house-door
        text: "Home"
        file: index.qmd
      - icon: file-person
        text: "About"
        file: about.qmd
  
  sidebar:
    style: floating
    search: true
    contents: auto
  
  page-footer: 
    left: 
      - href: https://mreyes.info
        text: mreyes.info
      - href: https://blog.mreyes.info
        text: blog
    center:
      - icon: code-slash
        href: https://github.com/keolasin/my_stats
    right:
      - icon: envelope
        href: mailto:matthew@mreyes.info
      - icon: linkedin
        url: https://linkedin.com/u/reyesmatthew
      - icon: github
        url: https://github.com/keolasin
  back-to-top-navigation: true
  page-navigation: true
      
execute:
  freeze: auto

format:
  html:
    theme:
      light: a11y
      dark: vapor
    css: styles.css
    toc: true

editor: visual
google-analytics: "G-VMVLZT0XPQ"
