project:
  type: website

metadata-files: 
  - _website.yml

# execution on render
execute:
  freeze: auto

# html/styling stuff
format:
  html:
    theme:
      light: a11y
      dark: vapor
    css: styles.css
    toc: true

# rstudio option
editor: visual

# python
jupyter: python3
