project:
  type: website

metadata-files: 
  - _website.yml

# execution on render
execute:
  freeze: auto
  cache: false

# html/styling stuff
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

# rstudio option
editor: visual

# python
jupyter: python3
