project:
  type: website

metadata-files: 
  - _website.yml

# execution on render
execute:
  freeze: auto
  cache: false

# html/styling stuff
format:
  html:
    theme:
      light: [a11y, theme-light.scss]
      dark: [a11y, theme-dark.scss]
    css: styles.css
    toc: true

# rstudio option
editor: visual

# python
jupyter: python3
